version: "3.9"

services:
  postgres:
    image: "postgres:11.5"
    environment:
      - "POSTGRES_USER=test"
      - "POSTGRES_DB=test"
      - "POSTGRES_PASSWORD=test"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - .docker/postgresql:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m
        max-file: "3"

volumes:
  postgresql:
    driver_opts:
      type: tmpfs
      device: tmpfs